# Generated by Django 6.1 on 2026-08-19 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('nombre_centro', models.CharField(blank=True, default='', max_length=200)),
                ('empresa', models.CharField(blank=True, default='', max_length=150)),
                ('año', models.IntegerField(db_index=True)),
                ('fecha_instalacion', models.CharField(blank=True, default='', max_length=50)),
                ('tecnico_visita', models.CharField(blank=True, default='', max_length=150)),
                ('numero_ficha', models.CharField(blank=True, default='', max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado de Instalación',
                'verbose_name_plural': 'Certificados de Instalación',
                'ordering': ['-año', '-fecha_modificacion', 'location'],
                'unique_together': {('location', 'año')},
            },
        ),
    ]
