# Generated by Django 6.1 on 2026-08-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargadoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encargado de Área',
                'verbose_name_plural': 'Encargados de Área',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('encargado_principal', models.ForeignKey(blank=True, help_text='Encargado de área al que reporta habitualmente este técnico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='portal.encargadoarea')),
            ],
            options={
                'verbose_name': 'Técnico de Terreno',
                'verbose_name_plural': 'Técnicos de Terreno',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('encargado_principal', models.ForeignKey(blank=True, help_text='Encargado de área asignado por defecto para esta zona geográfica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas', to='portal.encargadoarea')),
            ],
            options={
                'verbose_name': 'Zona Geográfica / Área',
                'verbose_name_plural': 'Zonas Geográficas / Áreas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
