# Generated by Django 6.1 on 2026-08-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_encargadoarea_tecnico_zonageografica'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTicketEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ticket', models.CharField(choices=[('conexion', 'Ticket de Conexión'), ('falla_equipo', 'Ticket de Falla de Equipo'), ('falla_sensor', 'Ticket de Falla de Sensor')], max_length=50)),
                ('empresa', models.CharField(max_length=150)),
                ('centro', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=255)),
                ('asistente_nombre', models.CharField(max_length=150)),
                ('destinatarios_to', models.TextField()),
                ('destinatarios_cc', models.TextField(blank=True, default='')),
                ('es_prueba', models.BooleanField(default=False)),
                ('manual_adjunto', models.BooleanField(default=True)),
                ('datos_ticket', models.JSONField(blank=True, default=dict)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Ticket Enviado',
                'verbose_name_plural': 'Historial de Tickets Enviados',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='CentroContactoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Empresa o cliente (ej: Cermaq, Mowi, AquaChile)', max_length=150)),
                ('nombre_centro', models.CharField(help_text='Nombre del centro de cultivo', max_length=150)),
                ('codigo_location', models.CharField(blank=True, default='', help_text='Código o location (ej: ch-chidhuapi1, ce-pollollo)', max_length=100)),
                ('destinatarios_to', models.TextField(blank=True, default='', help_text='Correos principales (Para / TO) separados por coma, punto y coma o saltos de línea')),
                ('destinatarios_cc', models.TextField(blank=True, default='', help_text='Correos en copia (CC) separados por coma, punto y coma o saltos de línea')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('zona_geografica', models.ForeignKey(blank=True, help_text='Zona geográfica a la que pertenece el centro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_contacto', to='portal.zonageografica')),
            ],
            options={
                'verbose_name': 'Centro de Cultivo & Contactos para Tickets',
                'verbose_name_plural': 'Centros de Cultivo & Contactos para Tickets',
                'ordering': ['empresa', 'nombre_centro'],
            },
        ),
    ]
