# Generated by Django 6.1 on 2026-08-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_historialticketenviado_centrocontactoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial de la empresa (ej: Cermaq, AquaChile, Camanchaca)', max_length=150, unique=True)),
                ('codigo', models.CharField(blank=True, default='', help_text='Código corto opcional', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='centrocontactoticket',
            name='empresa_rel',
            field=models.ForeignKey(blank=True, help_text='Vínculo opcional con la entidad Empresa canónica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_ticket', to='portal.empresa'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='empresa_rel',
            field=models.ForeignKey(blank=True, help_text='Vínculo opcional con la entidad Empresa canónica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatarios', to='portal.empresa'),
        ),
    ]
